# Generated by Django 5.2.1 on 2025-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_network', models.CharField(choices=[('TRC20', 'TRC20'), ('BEP20', 'BEP20')], max_length=10)),
                ('wallet_address', models.CharField(max_length=255)),
                ('amount_usdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_code', models.CharField(max_length=255)),
                ('transaction_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
