version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: alesplus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aliafsar31344
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn alesplus.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"  # فقط به شبکه داخلی Docker باز باشه
    depends_on:
      - db
    environment:
      DB_NAME: alesplus_db
      DB_USER: postgres
      DB_PASSWORD: Aliafsar31344
      DB_HOST: db
      DB_PORT: 5432

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d  # کانفیگ Nginx را اینجا بذار
      - /etc/letsencrypt:/etc/letsencrypt  # گواهی SSL
    depends_on:
      - web
    networks:
      - default

volumes:
  postgres_data:

