# Generated by Django 5.2.1 on 2025-06-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0003_customuser_access_token_customuser_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
