# Generated by Django 5.2.1 on 2025-06-06 12:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0004_customuser_phone_number_customuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Verification code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('network', models.CharField(choices=[('TRC20', 'USDT (TRC20)'), ('ERC20', 'USDT (ERC20)'), ('BEP20', 'USDT (BEP20)')], max_length=10)),
                ('wallet_address', models.CharField(max_length=255)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_view.customuser')),
            ],
        ),
    ]
