# Generated by Django 5.2.1 on 2025-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0006_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('cooperation_type', models.CharField(choices=[('advertising', 'Advertising'), ('investment_invention', 'Investment for Inventions Only'), ('investment_metaverse', 'Investment for Metaverse Only'), ('infrastructure', 'Infrastructure Development / Data Engineering & Website'), ('corporate_connection', 'Connection with Major Corporate Supporters'), ('exchange_listing', 'Token Listing Collaboration on Major Exchanges'), ('other', 'Other')], max_length=50)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
